import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar"
import TransitionProvide from "../components/transitionProvider"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className="bg-red-100">
  
          <TransitionProvide>
              {children}
          </TransitionProvide>
  
        </body>
      </html>
    );
  }
  